// <auto-generated />
using System;
using FoundBoxSG.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoundBoxSG.Migrations
{
    [DbContext(typeof(FoundBoxSGContext))]
    [Migration("20251220113644_AddAdminAppUserSeed")]
    partial class AddAdminAppUserSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoundBoxSG.Data.FoundBoxSGUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cf8fb073-4a0f-4950-8336-1be9b6b64275",
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            FullName = "Admin User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBN8NZNJld0LHKUdx2njB+XgnTQa01ul80miMBdsmzS6RnpPAl7YBXoSoyVUO9n7Ew==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d6997951-7918-41b7-aebe-a2bcc127341f",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        },
                        new
                        {
                            Id = "4b3a8d1e-2f5c-4e7a-9b0d-1f2g3h4i5j6k",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3bd1ef3c-a49e-43b8-baa8-98fe971cb741",
                            Email = "John@localhost.com",
                            EmailConfirmed = true,
                            FullName = "John Kindleson",
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHN@LOCALHOST.COM",
                            NormalizedUserName = "JOHN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKWzPDUsIECSwYjXzpQkX+/hBQPCGSXQrGsNm1HADmA3uzyICx6zNDOBXhMs6Zv6xA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0a8cfe7a-aab8-4313-9e03-47290ce86cbe",
                            TwoFactorEnabled = false,
                            UserName = "John@localhost.com"
                        },
                        new
                        {
                            Id = "9c5f2b8a-1d6e-3c9b-7a4f-0e1d2c3b4a59",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a9bf9606-dbb6-46a6-ae8f-b7e1db9cb379",
                            Email = "Jane@localhost.com",
                            EmailConfirmed = true,
                            FullName = "Jane Kindleberry",
                            LockoutEnabled = false,
                            NormalizedEmail = "JANE@LOCALHOST.COM",
                            NormalizedUserName = "JANE@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGf1nSp3OgmLvwrCoIid9X4oIFEoX3QRk1CYKj6lzMFcqQUSu759190wR6MFlC/93Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9b8257fe-0bb8-4243-b9b2-be3c03220eda",
                            TwoFactorEnabled = false,
                            UserName = "Jane@localhost.com"
                        });
                });

            modelBuilder.Entity("FoundBoxSG.Domain.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AspNetUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalListings")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AspNetUserId")
                        .IsUnique()
                        .HasFilter("[AspNetUserId] IS NOT NULL");

                    b.ToTable("AppUser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AspNetUserId = "4b3a8d1e-2f5c-4e7a-9b0d-1f2g3h4i5j6k",
                            CreatedBy = "John",
                            DateCreated = new DateTime(2025, 12, 20, 19, 36, 43, 300, DateTimeKind.Local).AddTicks(8874),
                            IsBanned = false,
                            Nationality = "Singaporean",
                            ProfileImageUrl = "/user.png",
                            Region = "Tampines",
                            TotalListings = 1
                        },
                        new
                        {
                            Id = 2,
                            AspNetUserId = "9c5f2b8a-1d6e-3c9b-7a4f-0e1d2c3b4a59",
                            CreatedBy = "Jane",
                            DateCreated = new DateTime(2025, 12, 20, 19, 36, 43, 300, DateTimeKind.Local).AddTicks(8946),
                            IsBanned = false,
                            Nationality = "Singaporean",
                            ProfileImageUrl = "/user.png",
                            Region = "Bedok",
                            TotalListings = 1
                        },
                        new
                        {
                            Id = 3,
                            AspNetUserId = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            CreatedBy = "Admin",
                            DateCreated = new DateTime(2025, 12, 20, 19, 36, 43, 300, DateTimeKind.Local).AddTicks(8948),
                            IsBanned = false,
                            Nationality = "Singaporean",
                            ProfileImageUrl = "/user.png",
                            Region = "Singapore",
                            TotalListings = 0
                        });
                });

            modelBuilder.Entity("FoundBoxSG.Domain.Listings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniqueFeatures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Listings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "N/A",
                            Color = "Silver and Red",
                            CreatedBy = "John",
                            DateCreated = new DateTime(2025, 12, 20, 19, 36, 43, 300, DateTimeKind.Local).AddTicks(8215),
                            Description = "Set of car keys with a red keychain",
                            Images = "[]",
                            ItemCategory = "Keys",
                            ListingType = "Found",
                            Location = "Marina Bay Sands",
                            Title = "Found Keys",
                            UniqueFeatures = "Red keychain with a smiley face",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Gucci",
                            Color = "Black",
                            CreatedBy = "Jane",
                            DateCreated = new DateTime(2025, 12, 20, 19, 36, 43, 300, DateTimeKind.Local).AddTicks(8265),
                            Description = "Black leather wallet",
                            Images = "[]",
                            ItemCategory = "Wallet",
                            ListingType = "Lost",
                            Location = "Orchard Road",
                            Title = "Lost Wallet",
                            UniqueFeatures = "Gold emblem",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("FoundBoxSG.Domain.Matches", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.Property<int>("MatcherUserId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "John",
                            DateCreated = new DateTime(2025, 12, 20, 19, 36, 43, 300, DateTimeKind.Local).AddTicks(8549),
                            ListingId = 1,
                            MatcherUserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Jane",
                            DateCreated = new DateTime(2025, 12, 20, 19, 36, 43, 300, DateTimeKind.Local).AddTicks(8552),
                            ListingId = 2,
                            MatcherUserId = 1
                        });
                });

            modelBuilder.Entity("FoundBoxSG.Domain.Messages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Hello! Is this item still available?",
                            CreatedBy = "John",
                            DateCreated = new DateTime(2025, 12, 20, 19, 36, 43, 300, DateTimeKind.Local).AddTicks(8706),
                            MatchId = 1,
                            SenderUserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Content = "Yes, it is still available. Would you like to arrange a pickup?",
                            CreatedBy = "Jane",
                            DateCreated = new DateTime(2025, 12, 20, 19, 36, 43, 300, DateTimeKind.Local).AddTicks(8713),
                            MatchId = 2,
                            SenderUserId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ad2bcf0c-20db-474f-8407-5a6b159518ba",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "bd2bcf0c-20db-474f-8407-5a6b159518bb",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "cd2bcf0c-20db-474f-8407-5a6b159518bb",
                            Name = "Banned",
                            NormalizedName = "BANNED"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            RoleId = "ad2bcf0c-20db-474f-8407-5a6b159518ba"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FoundBoxSG.Domain.AppUser", b =>
                {
                    b.HasOne("FoundBoxSG.Data.FoundBoxSGUser", "AspNetUser")
                        .WithOne("AppUser")
                        .HasForeignKey("FoundBoxSG.Domain.AppUser", "AspNetUserId");

                    b.Navigation("AspNetUser");
                });

            modelBuilder.Entity("FoundBoxSG.Domain.Listings", b =>
                {
                    b.HasOne("FoundBoxSG.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FoundBoxSG.Data.FoundBoxSGUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FoundBoxSG.Data.FoundBoxSGUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoundBoxSG.Data.FoundBoxSGUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FoundBoxSG.Data.FoundBoxSGUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FoundBoxSG.Data.FoundBoxSGUser", b =>
                {
                    b.Navigation("AppUser");
                });
#pragma warning restore 612, 618
        }
    }
}
