// <auto-generated />
using System;
using FoundBoxSG.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoundBoxSG.Migrations
{
    [DbContext(typeof(FoundBoxSGContext))]
    [Migration("20251203065405_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoundBoxSG.Domain.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "John",
                            DateCreated = new DateTime(2025, 12, 3, 14, 54, 4, 391, DateTimeKind.Local).AddTicks(5310),
                            FullName = "John Doe",
                            Gender = "Male",
                            Nationality = "Singaporean",
                            Region = "Tampines",
                            UserName = "johndoe123"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Jane",
                            DateCreated = new DateTime(2025, 12, 3, 14, 54, 4, 391, DateTimeKind.Local).AddTicks(5316),
                            FullName = "Jane Gun",
                            Gender = "Female",
                            Nationality = "Singaporean",
                            Region = "Bedok",
                            UserName = "janegun987"
                        });
                });

            modelBuilder.Entity("FoundBoxSG.Domain.Listings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniqueFeatures")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Listings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "N/A",
                            Color = "Silver and Red",
                            CreatedBy = "John",
                            DateCreated = new DateTime(2025, 12, 3, 14, 54, 4, 391, DateTimeKind.Local).AddTicks(4835),
                            Description = "Set of car keys with a red keychain",
                            ItemCategory = "Keys",
                            ListingType = "Found",
                            Location = "Marina Bay Sands",
                            Title = "Found Keys",
                            UniqueFeatures = "Red keychain with a smiley face"
                        },
                        new
                        {
                            Id = 24,
                            Brand = "Gucci",
                            Color = "Black",
                            CreatedBy = "Jane",
                            DateCreated = new DateTime(2025, 12, 3, 14, 54, 4, 391, DateTimeKind.Local).AddTicks(4860),
                            Description = "Black leather wallet",
                            ItemCategory = "Wallet",
                            ListingType = "Lost",
                            Location = "Orchard Road",
                            Title = "Lost Wallet",
                            UniqueFeatures = "Gold emblem"
                        });
                });

            modelBuilder.Entity("FoundBoxSG.Domain.Matches", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoundListingId")
                        .HasColumnType("int");

                    b.Property<int>("LostListingId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "John",
                            DateCreated = new DateTime(2025, 12, 3, 14, 54, 4, 391, DateTimeKind.Local).AddTicks(5095),
                            FoundListingId = 1,
                            LostListingId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Jane",
                            DateCreated = new DateTime(2025, 12, 3, 14, 54, 4, 391, DateTimeKind.Local).AddTicks(5098),
                            FoundListingId = 3,
                            LostListingId = 4
                        });
                });

            modelBuilder.Entity("FoundBoxSG.Domain.Messages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceiverUserId")
                        .HasColumnType("int");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Hello! Is this item still available?",
                            CreatedBy = "John",
                            DateCreated = new DateTime(2025, 12, 3, 14, 54, 4, 391, DateTimeKind.Local).AddTicks(5217),
                            MatchId = 1,
                            ReceiverUserId = 2,
                            SenderUserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Yes, it is still available. Would you like to arrange a pickup?",
                            CreatedBy = "Jane",
                            DateCreated = new DateTime(2025, 12, 3, 14, 54, 4, 391, DateTimeKind.Local).AddTicks(5221),
                            MatchId = 1,
                            ReceiverUserId = 1,
                            SenderUserId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
