// <auto-generated />
using System;
using FoundBoxSG.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoundBoxSG.Migrations
{
    [DbContext(typeof(FoundBoxSGContext))]
    [Migration("20251221085210_AddIsReadToMessages")]
    partial class AddIsReadToMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoundBoxSG.Data.FoundBoxSGUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8634c423-44a2-4660-992d-6323e79fd881",
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            FullName = "Admin User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHavnjH2++y0SDKsPVBLZh/LKFs3806VFhK3Imt4acuW12ICduHkC24KQi2w/8eCHw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0d37c0ee-4807-45f3-b732-b7d14934ff64",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        },
                        new
                        {
                            Id = "4b3a8d1e-2f5c-4e7a-9b0d-1f2g3h4i5j6k",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a45ad46a-ca4e-4118-900c-44d928bc9a62",
                            Email = "John@localhost.com",
                            EmailConfirmed = true,
                            FullName = "John Kindleson",
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHN@LOCALHOST.COM",
                            NormalizedUserName = "JOHN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDbhKVUm4cidw5njL6Prc2UMpd99oJp528ViY4ewqKQJzUrbi3FM0Q8pOeMqwMmf7g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c4eb9084-ae7c-499b-b9f7-a503bf168c07",
                            TwoFactorEnabled = false,
                            UserName = "John@localhost.com"
                        },
                        new
                        {
                            Id = "9c5f2b8a-1d6e-3c9b-7a4f-0e1d2c3b4a59",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fca479a0-5685-4c6d-8cb4-5201e83eb8a0",
                            Email = "Jane@localhost.com",
                            EmailConfirmed = true,
                            FullName = "Jane Kindleberry",
                            LockoutEnabled = false,
                            NormalizedEmail = "JANE@LOCALHOST.COM",
                            NormalizedUserName = "JANE@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFj+SG3BznwmJgUzX6bCBY9eS9aUKdZiRA1Pd4+7RG/3m9TKKYzMBnRaXgGvdFGRNQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a19d4734-ddfa-4187-a1c1-56a71310e5be",
                            TwoFactorEnabled = false,
                            UserName = "Jane@localhost.com"
                        });
                });

            modelBuilder.Entity("FoundBoxSG.Domain.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AspNetUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AspNetUserId")
                        .IsUnique()
                        .HasFilter("[AspNetUserId] IS NOT NULL");

                    b.ToTable("AppUser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AspNetUserId = "4b3a8d1e-2f5c-4e7a-9b0d-1f2g3h4i5j6k",
                            CreatedBy = "John",
                            DateCreated = new DateTime(2025, 12, 21, 16, 52, 9, 569, DateTimeKind.Local).AddTicks(6754),
                            IsBanned = false,
                            Nationality = "Singaporean",
                            ProfileImageUrl = "/user.png",
                            Region = "Tampines"
                        },
                        new
                        {
                            Id = 2,
                            AspNetUserId = "9c5f2b8a-1d6e-3c9b-7a4f-0e1d2c3b4a59",
                            CreatedBy = "Jane",
                            DateCreated = new DateTime(2025, 12, 21, 16, 52, 9, 569, DateTimeKind.Local).AddTicks(6756),
                            IsBanned = false,
                            Nationality = "Singaporean",
                            ProfileImageUrl = "/user.png",
                            Region = "Bedok"
                        },
                        new
                        {
                            Id = 3,
                            AspNetUserId = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            CreatedBy = "Admin",
                            DateCreated = new DateTime(2025, 12, 21, 16, 52, 9, 569, DateTimeKind.Local).AddTicks(6758),
                            IsBanned = false,
                            Nationality = "Singaporean",
                            ProfileImageUrl = "/user.png",
                            Region = "Singapore"
                        });
                });

            modelBuilder.Entity("FoundBoxSG.Domain.Listings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniqueFeatures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Listings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "N/A",
                            Color = "Silver and Red",
                            CreatedBy = "John",
                            DateCreated = new DateTime(2025, 12, 21, 16, 52, 9, 569, DateTimeKind.Local).AddTicks(6390),
                            Description = "Set of car keys with a red keychain",
                            Images = "[]",
                            ItemCategory = "Keys",
                            ListingType = "Found",
                            Location = "Marina Bay Sands",
                            Title = "Found Keys",
                            UniqueFeatures = "Red keychain with a smiley face",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Gucci",
                            Color = "Black",
                            CreatedBy = "Jane",
                            DateCreated = new DateTime(2025, 12, 21, 16, 52, 9, 569, DateTimeKind.Local).AddTicks(6405),
                            Description = "Black leather wallet",
                            Images = "[]",
                            ItemCategory = "Wallet",
                            ListingType = "Lost",
                            Location = "Orchard Road",
                            Title = "Lost Wallet",
                            UniqueFeatures = "Gold emblem",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("FoundBoxSG.Domain.Matches", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.Property<int>("MatcherUserId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "John",
                            DateCreated = new DateTime(2025, 12, 21, 16, 52, 9, 569, DateTimeKind.Local).AddTicks(6607),
                            ListingId = 1,
                            MatcherUserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Jane",
                            DateCreated = new DateTime(2025, 12, 21, 16, 52, 9, 569, DateTimeKind.Local).AddTicks(6610),
                            ListingId = 2,
                            MatcherUserId = 1
                        });
                });

            modelBuilder.Entity("FoundBoxSG.Domain.Messages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Hello! Is this item still available?",
                            CreatedBy = "John",
                            DateCreated = new DateTime(2025, 12, 21, 16, 52, 9, 569, DateTimeKind.Local).AddTicks(6689),
                            IsRead = false,
                            MatchId = 1,
                            SenderUserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Content = "Yes, it is still available. Would you like to arrange a pickup?",
                            CreatedBy = "Jane",
                            DateCreated = new DateTime(2025, 12, 21, 16, 52, 9, 569, DateTimeKind.Local).AddTicks(6691),
                            IsRead = false,
                            MatchId = 2,
                            SenderUserId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ad2bcf0c-20db-474f-8407-5a6b159518ba",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "bd2bcf0c-20db-474f-8407-5a6b159518bb",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "cd2bcf0c-20db-474f-8407-5a6b159518bb",
                            Name = "Banned",
                            NormalizedName = "BANNED"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            RoleId = "ad2bcf0c-20db-474f-8407-5a6b159518ba"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FoundBoxSG.Domain.AppUser", b =>
                {
                    b.HasOne("FoundBoxSG.Data.FoundBoxSGUser", "AspNetUser")
                        .WithOne("AppUser")
                        .HasForeignKey("FoundBoxSG.Domain.AppUser", "AspNetUserId");

                    b.Navigation("AspNetUser");
                });

            modelBuilder.Entity("FoundBoxSG.Domain.Listings", b =>
                {
                    b.HasOne("FoundBoxSG.Domain.AppUser", "User")
                        .WithMany("Listings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FoundBoxSG.Data.FoundBoxSGUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FoundBoxSG.Data.FoundBoxSGUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoundBoxSG.Data.FoundBoxSGUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FoundBoxSG.Data.FoundBoxSGUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FoundBoxSG.Data.FoundBoxSGUser", b =>
                {
                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("FoundBoxSG.Domain.AppUser", b =>
                {
                    b.Navigation("Listings");
                });
#pragma warning restore 612, 618
        }
    }
}
